
when:
  branch: main
  event: [push, pull_request, tag]

variables:
  - &repo source.hodakov.me/${CI_REPO_OWNER}/phpbb

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx:5.1.0
    privileged: true
    settings:
      dockerfile: Dockerfile
      platforms: linux/arm64/v8,linux/amd64
      dry_run: true
      repo: *repo
      auto_tag: true
    when:
      event: pull_request

  publish:
    image: woodpeckerci/plugin-docker-buildx:5.1.0
    privileged: true
    settings:
      dockerfile: Dockerfile
      platforms: linux/arm64/v8,linux/amd64
      repo: *repo
      registry: source.hodakov.me
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: registry_token
    when:
      event: [push, tag]
